use_frameworks!

platform :ios, '8.0'

target 'MDIZuJianHua_Example' do
  pod 'MDIZuJianHua', :path => '../'

  target 'MDIZuJianHua_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
